version: '3'

services:
  reverse-proxy_nginx:
    build: ./
    image: reverse-proxy_nginx
    container_name: reverse-proxy_nginx
    ports:
      - '80:80'
    networks:
      nginx_net:
        ipv4_address: 172.16.0.2
    volumes:
      - type: bind
        source: "./conf.d/default.conf"
        target: "/etc/nginx/conf.d/default.conf"
    restart: always

networks:
  nginx_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
