version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse-proxy
    ports:
      - '80:80'
    networks:
      nginx_net:
        ipv4_address: 172.16.0.2
    volumes:
      - type: bind
        source: "./conf.d/default.conf"
        target: "/etc/nginx/conf.d/default.conf"
    links:
      - nginx-kakeibosan
      - nginx-kakuninsan
    restart: always

networks:
  nginx_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
